---
- hosts: all

  become: yes
  gather_facts: False 

  tasks: 
    # - name: Update system
      # yum: 
        # name: "*"
        # state: latest

    - name: Update dnf
      dnf: 
        name: dnf
        state: latest

    - name: Install dnf-automatic
      dnf: 
        name: dnf-automatic
        state: present

    - name: Enable automatic updates
      lineinfile: 
        dest: /etc/dnf/automatic.conf
        regexp: "apply_updates = " 
        line: "apply_updates = yes"

    - name: Start dnf-automatic
      service:
        name: dnf-automatic.timer
        state: started
        enabled: yes
  
