#!/bin/bash

PACKAGES=( 
NetworkManager
NetworkManager-libnm
NetworkManager-team
NetworkManager-tui
acl
audit-libs
authselect
authselect-libs
basesystem
bash
biosdevname
brotli
bzip2-libs
ca-certificates
centos-gpg-keys
centos-release
centos-repos
chkconfig
chrony
coreutils
coreutils-common
cpio
cracklib
cracklib-dicts
crontabs
crypto-policies
cryptsetup-libs
curl
cyrus-sasl-lib
dbus
dbus-common
dbus-daemon
dbus-glib
dbus-libs
dbus-tools
device-mapper
device-mapper-libs
diffutils
dnf
dnf-data
dnf-plugin-spacewalk
dnf-plugins-core
dracut
dracut-config-rescue
e2fsprogs
e2fsprogs-libs
elfutils-default-yama-scope
elfutils-libelf
elfutils-libs
epel-release
ethtool
expat
file
file-libs
filesystem
findutils
fipscheck
fipscheck-lib
freetype
fuse-libs
gawk
gdbm
gdbm-libs
gettext
gettext-libs
glib2
glibc
glibc-common
glibc-langpack-en
gmp
gnupg2
gnupg2-smime
gnutls
gobject-introspection
gpgme
grep
groff-base
grub2-common
grub2-pc
grub2-pc-modules
grub2-tools
grub2-tools-extra
grub2-tools-minimal
grubby
gzip
hardlink
hostname
htop
hwdata
ima-evm-utils
info
initscripts
iproute
iprutils
iptables-libs
iputils
irqbalance
iwl100-firmware
iwl1000-firmware
iwl105-firmware
iwl135-firmware
iwl2000-firmware
iwl2030-firmware
iwl3160-firmware
iwl3945-firmware
iwl4965-firmware
iwl5000-firmware
iwl5150-firmware
iwl6000-firmware
iwl6000g2a-firmware
iwl6050-firmware
iwl7260-firmware
jansson
json-c
kbd
kbd-legacy
kbd-misc
kernel
kernel-core
kernel-modules
kernel-tools
kernel-tools-libs
keyutils-libs
kmod
kmod-libs
kpartx
krb5-libs
langpacks-en
less
libacl
libarchive
libassuan
libattr
libblkid
libcap
libcap-ng
libcom_err
libcomps
libcroco
libcurl
libdaemon
libdb
libdb-utils
libdnf
libedit
libevent
libfdisk
libffi
libgcc
libgcrypt
libgomp
libgpg-error
libgudev
libidn2
libkcapi
libkcapi-hmaccalc
libksba
libmetalink
libmnl
libmodulemd1
libmount
libndp
libnghttp2
libnl3
libnl3-cli
libnsl2
libpcap
libpipeline
libpng
libpsl
libpwquality
librepo
libreport-filesystem
libseccomp
libsecret
libselinux
libselinux-utils
libsemanage
libsepol
libsigsegv
libsmartcols
libsolv
libss
libssh
libssh-config
libstdc++
libsysfs
libtasn1
libteam
libtirpc
libunistring
libusbx
libuser
libutempter
libuuid
libverto
libxcrypt
libxkbcommon
libxml2
libyaml
linux-firmware
lshw
lsscsi
lua-libs
lz4-libs
man-db
microcode_ctl
mpfr
ncurses
ncurses-base
ncurses-libs
nettle
newt
npth
numactl-libs
openldap
openssh
openssh-clients
openssh-server
openssl
openssl-libs
openssl-pkcs11
os-prober
p11-kit
p11-kit-trust
pam
parted
passwd
pciutils-libs
pcre
pcre2
pigz
pinentry
platform-python
platform-python-pip
platform-python-setuptools
plymouth
plymouth-core-libs
plymouth-scripts
policycoreutils
polkit-libs
popt
prefixdevname
procps-ng
publicsuffix-list-dafsa
python3-asn1crypto
python3-cffi
python3-cryptography
python3-dateutil
python3-dbus
python3-dmidecode
python3-dnf
python3-dnf-plugin-spacewalk
python3-dnf-plugins-core
python3-gobject-base
python3-gpg
python3-hawkey
python3-hwdata
python3-idna
python3-libcomps
python3-libdnf
python3-librepo
python3-libs
python3-libselinux
python3-libxml2
python3-netifaces
python3-newt
python3-pip-wheel
python3-ply
python3-pyOpenSSL
python3-pycparser
python3-rhn-client-tools
python3-rhnlib
python3-rpm
python3-setuptools-wheel
python3-six
python3-unbound
qemu-guest-agent
readline
rhn-client-tools
rng-tools
rootfiles
rpm
rpm-build-libs
rpm-libs
rpm-plugin-selinux
rpm-plugin-systemd-inhibit
sed
selinux-policy
selinux-policy-targeted
setup
sg3_utils
sg3_utils-libs
shadow-utils
shared-mime-info
slang
sqlite-libs
sudo
systemd
systemd-libs
systemd-pam
systemd-udev
teamd
trousers
trousers-lib
tzdata
unbound-libs
util-linux
vim-minimal
which
xfsprogs
xkeyboard-config
xz
xz-libs
yum
zlib

# LVM
lvm2
device-mapper-event
device-mapper-event-libs
device-mapper-persistent-data
libaio
lvm2-libs

# cronie
# cronie-anacron
# iptables
# iptables
# libnetfilter_conntrack
# libnfnetlink
# libnftnl

# kexec-tools
# bind-export-libs
# dhcp-client
# dhcp-common
# dhcp-libs
# dracut-network
# dracut-squash
# geolite2-city
# geolite2-country
# ipcalc
# libmaxminddb
# lzo
# snappy
# squashfs-tools
)

in_array() {
    # Checks if an element is contained in the array.
    #
    # Args:
    #    array_name - name of the global array
    #
    # Returns:
    #    0 if element is found, 1 otherwise.

    local array_name="$1[@]"
    local array=( "${!array_name}" )
    local element="$2"

    for (( i = 0; i < "${#array[@]}"; i++ )); do
        if [[ "$element" == "${array[i]}" ]]; then
            return 0
        fi
    done
    return 1
}

remove=()
while read -r package; do
    if ! in_array PACKAGES "$package"; then
	remove+=( "$package" )
    fi
done <<< $( dnf list installed | awk -F'.' '(NR > 1) { print $1 }' )

if [[ ! "$1" ]]; then
    echo "dnf remove ${remove[*]}"
else
    eval "dnf -y remove ${remove[*]}"
fi
